FUNCTION FCONVASC RETURN LONGCHAR (INPUT P-IN_STR AS LONGCHAR):
    DEF VAR IX       AS INT      NO-UNDO.
    DEF VAR VCHR     AS CHAR     NO-UNDO.
    DEF VAR VNEW_STR AS LONGCHAR NO-UNDO.
    REPEAT IX = 1 TO LENGTH(P-IN_STR):
      ASSIGN VCHR = SUBSTRING(P-IN_STR,IX,1).
      IF ASC(VCHR) >= 32 AND ASC(VCHR) <= 255 THEN VNEW_STR = VNEW_STR + VCHR.
    END.
    RETURN VNEW_STR.
END FUNCTION.
